[package]
name = "bake-config"
version = "0.1.0"
edition = "2021"

[dependencies]
# 使用 workspace 依赖
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

# 内部依赖
bake-common = { path = "../common" }
