[package]
name = "bake-config"
version = "0.1.0"
edition = "2021"

[dependencies]
# 内部依赖
bake-common = { path = "../common" }
thiserror = "1.0"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
