[package]
name = "bake-common"
version = "0.1.0"
edition = "2021"

[dependencies]
# 使用 workspace 依赖
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
